spring:
  application:
    name: boot-backend
  security:
    jwt:
      key: example
      expires: 168
  data:
    redis:
      host: localhost
      port: 6379
    jdbc:
      dialect: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/jwt
    username: root
    password: 12345
logging:
  level:
    root: info